name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo da sua branch padrão

permissions:
  contents: write  # Necessário para push na branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Blazor WebAssembly app
        run: dotnet publish -c Release -o build_output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_output/wwwroot
          publish_branch: gh-pages
          force_orphan: true  # sobrescreve histórico da branch

      - name: Add .nojekyll file
        run: touch build_output/wwwroot/.nojekyll

